modLoader="javafml" #mandatory
loaderVersion="[25,)" #mandatory (24 is current forge version)
# A list of mods - how many allowed here is determined by the individual mod loader
[[mods]] #mandatory
modId="drewcraftmod" #mandatory
version="0.1"      #mandatory
displayName="DrewCraft Mod" #mandatory
credits="Thanks for this example mod goes to HarryTalks and LoreMaster" #optional
description='''
This is my first attempt at a mod.
So far so good.
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.drewcraftmod]] #optional
    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[25,)" #mandatory
    ordering="NONE"
    side="BOTH"
[[dependencies.drewcraftmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.13.2]"
    ordering="NONE"
    side="BOTH"